[run]
init_cmds = [
  ["./bin/grafana", "server", "-packaging=dev", "cfg:app_mode=development","--log-level=none"]
]
watch_all = true
follow_symlinks = true
watch_dirs = [

]
watch_exts = []
ignore_files = [".*_gen.go"]
build_delay = 1500
cmds = [
  ["./bin/grafana", "server", "-packaging=dev", "cfg:app_mode=development","--log-level=none"]
]
